# Generated by Django 3.1.5 on 2021-02-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0002_auto_20210131_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzashop',
            name='logo',
            field=models.ImageField(blank=True, upload_to='pizzashop_logo/'),
        ),
    ]
